version: 0
tasks:
  - provisionerId: "{{ taskcluster.docker.provisionerId }}"
    workerType: "{{ taskcluster.docker.workerType }}"
    extra:
      github:
        env: true
        events:
          - push
          - pull_request.opened
          - pull_request.synchronize
          - pull_request.reopened
    scopes:
      - secrets:get:project/taskcluster/testing/taskcluster-pulse
    payload:
      maxRunTime: 3600
      # this image was built from test/Dockerfile; it's a mashup of the given node and rabbitmq images..
      image: "taskcluster/taskcluster-pulse-test:node-8.11.2-rabbitmq-3.6.15-management@sha256:727392ce1d90f848496792636593fca72e9304b0c6064b401aeefd4bf1a27c26"
      env:
        NO_TEST_SKIP: true
        # this affects the image, and makes it allow guest:guest access to the /test vhost
        RABBITMQ_DEFAULT_VHOST: /test
      features:
        taskclusterProxy: true
      command:
        - "/bin/bash"
        - "--login"
        - "-c"
        # This starts the rabbitmq server and waits for it to come up; note that there's no need
        # to shut it down, as the docker container termination will clean it up.
        - >-
            git clone {{event.head.repo.url}} repo &&
            cd repo &&
            git checkout {{event.head.sha}} &&
            yarn &&
            yarn global add wait-port &&
            { docker-entrypoint.sh rabbitmq-server & wait-port 5672; } &&
            RABBIT_USERNAME=guest RABBIT_PASSWORD=guest RABBIT_BASE_URL=http://localhost:15672/api yarn test
    metadata:
      name: "Taskcluster Pulse Tests"
      description: "Tests"
      owner: "{{ event.head.user.email }}"
      source: "{{ event.head.repo.url }}"

