language: node_js
sudo: required # We must use sudo here to have rabbitmq running :(
env:
  global:
  - DEBUG='base:app:request,auth:*,server,test:*,pulse'
  - CXX=g++-4.8
  - RABBIT_USERNAME=guest
  - RABBIT_PASSWORD=guest
  - RABBIT_BASE_URL=http://localhost:15672/api 
node_js:
- '6'
cache:
  directories:
    - node_modules
services:
  - rabbitmq
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm test
