defaults:
  # Application specific configuration keys
  app:
    # Prefix for exchanges, should always be v1/
    exchangePrefix: v1/

  # taskcluster credentials the service should use
  taskcluster:
    credentials:      # Load strings from environment variables
      clientId:       !env TASKCLUSTER_CLIENT_ID
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN
  # Configuration for server
  server:
    publicUrl:                https://pulse.taskcluster.net
    port:                     !env:number PORT
    env:                      !env NODE_ENV
    forceSSL:                 !env:bool FORCE_SSL
    trustProxy:               !env:bool TRUST_PROXY

production:
  server:
    forceSSL:                 true
    trustProxy:               true
    env:                      'production'

test:
  server:
    publicUrl:        http://localhost:60403
    port:             60403
    forceSSL:         false
    trustProxy:       false
    env:              development
