defaults:
  # Application specific configuration keys
  app:
    # Prefix for exchanges, should always be v1/
    exchangePrefix: v1/
    namespaceTableName: 'PulseNamespaces'
    namespacesExpirationDelay: '- 1 hour'
    # If given, all namespaces must begin with this string; and only
    # matching queues and exchanges will be monitored.  Use this to
    # allow taskcluster-pulse to "share" a rabbitmq server with other
    # users.
    namespacePrefix: !env NAMESPACE_PREFIX
    # TODO: add virtualHost too
    amqpUrl: !env TASKCLUSTER_AMQP_URL

  aws:
    accessKeyId:      !env AWS_ACCESS_KEY_ID
    secretAccessKey:  !env AWS_SECRET_ACCESS_KEY
    region:           us-east-1
    apiVersion:       2014-01-01

  taskcluster:
    credentials:      # Load strings from environment variables
      clientId:       !env TASKCLUSTER_CLIENT_ID
      accessToken:    !env TASKCLUSTER_ACCESS_TOKEN

  server:
    publicUrl:                https://pulse.taskcluster.net
    port:                     !env:number PORT
    env:                      !env NODE_ENV
    forceSSL:                 !env:bool FORCE_SSL
    trustProxy:               !env:bool TRUST_PROXY

  rabbit:
    username:                 !env RABBIT_USERNAME
    password:                 !env RABBIT_PASSWORD
    baseUrl:                  !env RABBIT_BASE_URL

  azure:
    account:                  !env AZURE_ACCOUNT_NAME

  stressor:
    payloadSize:              !env STRESSOR_PAYLOAD_SIZE
    uploadRate:               !env STRESSOR_UPLOAD_RATE
    messageCount:             !env STRESSOR_MESSAGE_COUNT
    targetQueue:              !env STRESSOR_TARGET_QUEUE

  monitor:
    refreshInterval:              !env MONITOR_REFRESH_INTERVAL

  alerter:
    messageCountTolerance:        !env ALERTER_MESSAGE_COUNT_TOLERANCE
    messagePublishRateTolerance:  !env ALERTER_MESSAGE_PUBLISH_RATE_TOLERANCE

production:
  server:
    forceSSL:                 true
    trustProxy:               true
    env:                      'production'

test:
  app:
    amqpUrl: 'amqp://localhost'
    namespacePrefix: 'tcpulse-test-'

  taskcluster:
    credentials:
      clientId:       'test-client'
      accessToken:    'none'

  stressor:
    payloadSize: 20
    uploadRate: 50
    messageCount: 5
    targetQueue: 'stressor queue'

  server:
    publicUrl:        http://localhost:60403
    port:             60403
    forceSSL:         false
    trustProxy:       false
    env:              development

  azure:
    account:  "inMemory"

  monitor:
    refreshInterval: 1000
    queuePrefix: 'taskcluster/'

  alerter:
    messageCountTolerance: 10
    messagePublishRateTolerance: 5
